# Generated by Django 4.1.5 on 2023-01-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='address_line_1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='appuser',
            name='address_line_2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='appuser',
            name='city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
