# Generated by Django 4.1.5 on 2023-01-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appuser_address_line_1_appuser_address_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='address',
        ),
        migrations.AddField(
            model_name='appuser',
            name='zip_code',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='address_line_1',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='address_line_2',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='state',
            field=models.CharField(default='None', max_length=2),
        ),
    ]
