# Generated by Django 4.1.7 on 2023-03-13 17:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_appuser_address_appuser_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
