# Generated by Django 4.1.3 on 2023-03-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='state',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
