# Generated by Django 4.1.3 on 2022-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
