# Generated by Django 4.1.3 on 2023-02-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_listing_main_photo_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
