# Generated by Django 4.1.6 on 2023-02-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_main_photo', models.FileField(blank=True, null=True, upload_to='uploads/items/')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('owner', models.CharField(max_length=150)),
                ('listing', models.IntegerField()),
            ],
        ),
    ]
