# Generated by Django 4.1.6 on 2023-02-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.CharField(default=23432, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='lng',
            field=models.CharField(default=231, max_length=20),
            preserve_default=False,
        ),
    ]
