# Generated by Django 4.1.6 on 2023-02-20 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_item_date_item_lat_item_lng_item_tags_item_zip_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='date',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
