# Generated by Django 4.1.3 on 2023-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_date_item_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
