# Generated by Django 4.1.3 on 2023-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_item_description_alter_item_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_main_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_main_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
