# Generated by Django 4.1.6 on 2023-03-14 12:15

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_item_description_alter_item_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.item_directory_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.listing_directory_path),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_main_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_main_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
