# Generated by Django 4.1.3 on 2023-03-15 23:52

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_item_name_alter_listing_listing_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.listing_directory_path),
        ),
    ]
