# Generated by Django 4.1.6 on 2023-03-15 00:28

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_item_item_photo_url_listing_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_main_photo',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.item_directory_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_photo_url',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_photo_url',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.listing_directory_path),
        ),
    ]
