# Generated by Django 4.1.3 on 2023-03-16 02:53

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_item_item_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.item_directory_path),
        ),
    ]
