# Generated by Django 4.1.6 on 2023-06-15 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_favoriteitems_item_alter_favoriteitems_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
