# Generated by Django 4.1.3 on 2022-11-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresstable',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('apt', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('states', models.CharField(blank=True, max_length=45, null=True)),
                ('zip', models.CharField(blank=True, max_length=45, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addresstable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garagesaletable',
            fields=[
                ('gsid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('lid', models.IntegerField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('aid', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'garagesaletable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagetable',
            fields=[
                ('itid', models.AutoField(primary_key=True, serialize=False)),
                ('iid', models.IntegerField(blank=True, null=True)),
                ('src', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imagetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemlisttable',
            fields=[
                ('ltid', models.AutoField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('itid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemlisttable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemtable',
            fields=[
                ('itid', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(blank=True, max_length=45, null=True)),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('mnumber', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('gsid', models.IntegerField(blank=True, null=True)),
                ('posttime', models.DateTimeField(blank=True, null=True)),
                ('imageid', models.IntegerField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('display', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordertable',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('lid', models.IntegerField(blank=True, null=True)),
                ('ordertime', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('billing', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ordertable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testtable',
            fields=[
                ('itid', models.IntegerField(db_column='ITID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'testtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('registertime', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('profilepicture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usertable',
                'managed': False,
            },
        ),
    ]
